{% set version = "2.1.3" %}
{% set version_url = "2.1-3" %}

package:
  name: cunit
  version: {{ version }}

source:
  - url: https://sourceforge.net/projects/cunit/files/CUnit/{{ version_url }}/CUnit-{{ version_url }}.tar.bz2
    md5: b5f1a9f6093869c070c6e4a9450cc10c
  - path: CMakeLists.txt  # [win]

build:
  number: 1002

requirements:
  build:
    - libtool
    - autoconf
    - automake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libcunit.a
    - test -f ${PREFIX}/lib/libcunit.so  # [linux]
    - test -f ${PREFIX}/lib/libcunit.dylib  # [osx]

about:
  home: http://sourceforge.net/projects/cunit/
  license: LGPL v2
  summary: A Unit Testing Framework for C

extra:
    recipe-maintainers:
      - grlee77
      - wolfv